package loccounter;

import java.awt.ComponentOrientation;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Sirlopu
 */
public class GUI extends javax.swing.JFrame {

    LOCCounter count;
    
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        browseButton = new javax.swing.JButton();
        selectFileLabel = new javax.swing.JLabel();
        selectedFileTextField = new javax.swing.JTextField();
        countButton = new javax.swing.JButton();
        totalLOCTextField = new javax.swing.JTextField();
        totalLOCLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        aboutMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOC Counter by Sirlopu");

        browseButton.setText("Browse");
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });

        selectFileLabel.setText("Select source file : ");
        selectFileLabel.setToolTipText("Select the file you would like to count LOC");

        selectedFileTextField.setEditable(false);

        countButton.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        countButton.setText("Count LOC");

        totalLOCTextField.setEditable(false);
        totalLOCTextField.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        totalLOCTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        totalLOCLabel.setText("Total LOC : ");

        aboutMenu.setText("About");
        aboutMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(aboutMenu);

        jMenuBar1.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(25, 25, 25)
                .add(selectFileLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(selectedFileTextField)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(browseButton)
                .add(16, 16, 16))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(241, Short.MAX_VALUE)
                .add(totalLOCLabel)
                .add(34, 34, 34)
                .add(totalLOCTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 95, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(246, 246, 246))
            .add(layout.createSequentialGroup()
                .add(256, 256, 256)
                .add(countButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 178, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(48, 48, 48)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(browseButton)
                    .add(selectFileLabel)
                    .add(selectedFileTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(countButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 53, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(17, 17, 17)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(totalLOCTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(totalLOCLabel))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-690)/2, (screenSize.height-284)/2, 690, 284);
    }// </editor-fold>//GEN-END:initComponents
    
    //"Browse" button event code
    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonActionPerformed
        
        //create new file chooser
        JFileChooser fc = new JFileChooser();
        
        //set window title for file chooser
        fc.setDialogTitle("Choose source code file to count LOC");
        
        int rVal = fc.showOpenDialog(GUI.this);
        
        if (rVal == JFileChooser.APPROVE_OPTION){
            
            //set file name to the selected file text field
            selectedFileTextField.setText(fc.getSelectedFile().getAbsolutePath());
            
            //create file object from selected file
            File source = fc.getSelectedFile();
            
            count = new LOCCounter();
            totalLOCTextField.setText(count.counter(source));
        }
        
        //catches event if user does not select file in file chooser
        if (rVal == JFileChooser.CANCEL_OPTION){
            
            //display notification when no file is selected
            selectedFileTextField.setText("None selected");
        }
    }//GEN-LAST:event_browseButtonActionPerformed
    
    private void aboutMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutMenuMouseClicked
        JOptionPane.showMessageDialog(null, "Developed by Sirlopu \n" + "Lines starting with the following characters/text are excluded from the LOC counter : \n" +
                " */, " + " *, " + " //, " + " \\, " + " }, " + " package, " + " import. "
                , "LOC Counter", JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_aboutMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu aboutMenu;
    private javax.swing.JButton browseButton;
    private javax.swing.JButton countButton;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel selectFileLabel;
    private javax.swing.JTextField selectedFileTextField;
    private javax.swing.JLabel totalLOCLabel;
    private javax.swing.JTextField totalLOCTextField;
    // End of variables declaration//GEN-END:variables
}
